version: '3.8'
services:
  web:
    image: node:alpine
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000
    command: ash -c "npm i && npm run dev:calledFromDockerCompose"
  db:
    image: mongo
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
